---
title: "T-tests with Boxplots"
author: "Uyen 'Rachel' Lai and Paul Sheridan"
output: html_notebook
---


```{r setup, include = FALSE}
# Specify global settings
knitr::opts_chunk$set(echo = TRUE)

# Start fresh by clearing R environment
rm(list = ls())
```


```{r}
# Load required libraries
library(tidyverse)
library(GGally)
library(ggpubr) # ANOVA boxplots
library(RColorBrewer)
library(scales)
library(here) # Simplify file i/o

# Custom colors
hex <- hue_pal()(3)
gg_red <- hex[1]
gg_green <- hex[2]
gg_blue <- hex[3]
gg_orange <- brewer.pal(n = 11, name = "PuOr")[4]
gg_purple <- "#C77CFF"

# Custom palette
my_palette <- c("human" = gg_red, "llm" = gg_green, "gptneo" = gg_blue, "pythia" = gg_orange, "opt" = gg_purple)
```




## Load and Prepare Data

```{r}
# Load the raw data:
file_path  <- "../../data/llm_and_human_heapslaw_stats.csv"
rawdata <- read.csv(file_path, stringsAsFactors = FALSE)
```


```{r}
# Create wrangled data frame:
basic_dat <- rawdata |>
  select(-c(file_name, mean, s.d, vocab_size, total_words, alpha, singleton_count, r)) |> # Drop irrelevant columns
  mutate(
    vocab = factor(vocab, levels = c("open", "closed")),
    prompt = factor(prompt, levels = c("none", "zeroshot", "oneshot", "fewshot")),
    model_name = factor(model_name, levels = c("human", "gptneo", "pythia", "opt")),
    corpus = factor(corpus, levels = c("pubmed", "book2", "hn", "wiki")),
    model_size = factor(
      case_when(
        model_size %in% c("none") ~ "none",
        model_size %in% c("70m", "125m", "160m", "350m", "410m") ~ "small",
        model_size %in% c("1b", "1.3b", "1.4b", "2.7b", "2.8b") ~ "big"
      ),
      levels = c("none", "small", "big")
    ),
  )

# Create data frame for pooled AI models:
llm_dat <- basic_dat |>
  filter(model_name != "human") |>
  mutate(
    model_name = factor(
      case_when(
        as.character(model_name) %in% c("gptneo", "pythia", "opt") ~ "llm"
      )
    )
  )

# Merge and sort data frames:
dat <- basic_dat |>
  bind_rows(llm_dat) |>
  mutate(model_name = factor(model_name, levels = c("human", "llm", "gptneo", "pythia", "opt"))) |>
  arrange(vocab, corpus, model_name, model_size, prompt)

# Print to console:
dat
```



## Boxplots

### Open Vocab Setting

```{r}
# Extract open vocab setting subdata:
dat_open <- dat |>
  filter(vocab == "open") |>
  select(-c("vocab"))

# Print to console:  
dat_open
```



```{r}
# Set up plot data:
x <- which(names(dat_open) == "model_name") # name of grouping variable
y <- which(names(dat_open) == "beta") # names of variables to test
my_comparisons <- list(c("human", "llm"), c("human", "gptneo"), c("human", "pythia"), c("human", "opt")) # comparisons for post-hoc tests

# Create boxplot:
p <- ggboxplot(
  dat_open,
  x = colnames(dat_open[x]),
  y = "beta",
  fill = "transparent",  # ENSURE TRANSPARENCY INSIDE BOX


  color = colnames(dat_open[x]),
  legend = "none",
  palette = my_palette,
  add = "jitter") +
  ggtitle("Open vocabulary setting") +
  xlab("") +
  ylab("Beta") +
  stat_compare_means(comparisons = my_comparisons, method = "t.test", method.args = list(alternative = "less"), label = "p.format") + # remove if p-value of ANOVA or Kruskal-Wallis test >= alpha
  scale_x_discrete(labels = c("human" = "Human", "llm" = "LLM", "gptneo" = "GPT-Neo", "pythia" = "Pythia", "opt" = "OPT")) +
  theme_minimal(base_size = 14) +
  theme(
    panel.background = element_rect(fill = "transparent", color = NA),  
    plot.background = element_rect(fill = "transparent", color = NA),   
    legend.position = "none",  
    panel.grid = element_blank(), 
    axis.line = element_line(color = "black"),  
    strip.background = element_rect(fill = "transparent", color = NA),  
    strip.text = element_text(color = "black"),
    panel.border = element_blank()  # Ensures no extra borders
  )

# Save to plot to PDF with transparent background:
ggsave(
  plot = p, 
  filename = here("beta-boxplots-open-vocab.pdf"),
  device = "pdf",
  width = 6,
  height = 6,
  units = "in",
  dpi = 320,
  limitsize = FALSE,
  bg       = "transparent"

)
```




### Closed Vocab Setting

```{r}
# Extract open vocab setting subdata:
dat_closed <- dat |>
  filter(vocab == "closed") |>
  select(-c("vocab"))

# Print to console:  
dat_closed
```



```{r}
# Set up plot data:
x <- which(names(dat_closed) == "model_name") # name of grouping variable
y <- which(names(dat_closed) == "beta") # names of variables to test
my_comparisons <- list(c("human", "llm"), c("human", "gptneo"), c("human", "pythia"), c("human", "opt")) # comparisons for post-hoc tests

# Create boxplot:
p <- ggboxplot(
  dat_closed,
  x = colnames(dat_closed[x]),
  y = "beta",
  color = colnames(dat_closed[x]),
  legend = "none",
  palette = my_palette,
  add = "jitter") +
  ggtitle("Closed vocabulary setting") +
  xlab("") +
  ylab("Beta") +
  stat_compare_means(comparisons = my_comparisons, method = "t.test", method.args = list(alternative = "less"), label = "p.format") + # remove if p-value of ANOVA or Kruskal-Wallis test >= alpha
  scale_x_discrete(labels = c("human" = "human", "llm" = "LLM", "gptneo" = "GPT-Neo", "pythia" = "Pythia", "opt" = "OPT"))+
  theme_minimal(base_size = 14) +
  theme(
    panel.background = element_rect(fill = "transparent", color = NA),  
    plot.background = element_rect(fill = "transparent", color = NA),   
    legend.position = "none",  
    panel.grid = element_blank(), 
    axis.line = element_line(color = "black"),  
    strip.background = element_rect(fill = "transparent", color = NA),  
    strip.text = element_text(color = "black"),
    panel.border = element_blank()  # Ensures no extra borders
  )

# Print to console:
print(p)

# Save to plot to PDF with transparent background:
ggsave(
  plot = p, 
  filename = here("beta-boxplots-closed-vocab.pdf"),
  device = "pdf",
  width = 6,
  height = 6,
  units = "in",
  dpi = 320,
  limitsize = FALSE,
  bg       = "transparent"

)
```





